import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { Client, Storage as AppwriteStorage } from 'node-appwrite';
import { InputFile } from 'node-appwrite/file';
import { getEnv } from './env';

export interface StoredFile {
  key: string;
  contentType: string;
  size: number;
}

export interface StorageDriver {
  put(key: string, data: Buffer, contentType: string): Promise<StoredFile>;
  get(key: string): Promise<{ data: Buffer; contentType: string } | null>;
  delete(key: string): Promise<void>;
}

// ---------------------------------------------------------------------
// Local filesystem (dev only -- no persistent disk on a serverless deploy)
// ---------------------------------------------------------------------

const CONTENT_TYPE_SIDECAR_SUFFIX = '.contenttype';

class LocalStorageDriver implements StorageDriver {
  constructor(private readonly root: string) {}

  private resolve(key: string): string {
    // Keys are always generated by this app (uuid-based directories), but
    // guard against path traversal regardless of origin.
    if (key.includes('..')) throw new Error(`Invalid storage key: ${key}`);
    return join(this.root, key);
  }

  async put(key: string, data: Buffer, contentType: string): Promise<StoredFile> {
    const path = this.resolve(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, data);
    await writeFile(`${path}${CONTENT_TYPE_SIDECAR_SUFFIX}`, contentType, 'utf8');
    return { key, contentType, size: data.byteLength };
  }

  async get(key: string): Promise<{ data: Buffer; contentType: string } | null> {
    const path = this.resolve(key);
    try {
      const data = await readFile(path);
      const contentType = await readFile(`${path}${CONTENT_TYPE_SIDECAR_SUFFIX}`, 'utf8').catch(
        () => 'application/octet-stream',
      );
      return { data, contentType };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    const path = this.resolve(key);
    await rm(path, { force: true });
    await rm(`${path}${CONTENT_TYPE_SIDECAR_SUFFIX}`, { force: true });
  }
}

// ---------------------------------------------------------------------
// Appwrite Storage
// ---------------------------------------------------------------------

class AppwriteStorageDriver implements StorageDriver {
  private readonly storage: AppwriteStorage;

  constructor(
    endpoint: string,
    projectId: string,
    apiKey: string,
    private readonly bucketId: string,
  ) {
    const client = new Client().setEndpoint(endpoint).setProject(projectId).setKey(apiKey);
    this.storage = new AppwriteStorage(client);
  }

  async put(key: string, data: Buffer, contentType: string): Promise<StoredFile> {
    const fileId = toAppwriteId(key);
    const file = InputFile.fromBuffer(data, key);
    // Server-key upload only. Nothing here is meant to be readable
    // directly from a browser -- every read is mediated by our own API,
    // which applies this app's own permission model, not Appwrite's.
    await this.storage.createFile({ bucketId: this.bucketId, fileId, file });
    return { key, contentType, size: data.byteLength };
  }

  async get(key: string): Promise<{ data: Buffer; contentType: string } | null> {
    const fileId = toAppwriteId(key);
    try {
      const [meta, bytes] = await Promise.all([
        this.storage.getFile({ bucketId: this.bucketId, fileId }),
        this.storage.getFileView({ bucketId: this.bucketId, fileId }),
      ]);
      return { data: Buffer.from(bytes), contentType: meta.mimeType || 'application/octet-stream' };
    } catch (err) {
      if (isAppwriteNotFound(err)) return null;
      throw err;
    }
  }

  async delete(key: string): Promise<void> {
    const fileId = toAppwriteId(key);
    try {
      await this.storage.deleteFile({ bucketId: this.bucketId, fileId });
    } catch (err) {
      if (!isAppwriteNotFound(err)) throw err;
    }
  }
}

function isAppwriteNotFound(err: unknown): boolean {
  return typeof err === 'object' && err !== null && (err as { code?: number }).code === 404;
}

/**
 * Appwrite file/bucket IDs are capped at 36 chars and restricted to
 * a-z A-Z 0-9 . - _ (and can't start with a special char), but our keys
 * are slash-delimited paths like `sources/<uuid>/original.pdf`. Hashing
 * the key down to a stable id keeps the mapping deterministic without
 * needing a separate lookup table; the original key is kept as the
 * uploaded file's name for anyone browsing the Appwrite console.
 */
function toAppwriteId(key: string): string {
  return `f${createHash('sha256').update(key).digest('hex').slice(0, 35)}`;
}

// ---------------------------------------------------------------------
// Driver selection
// ---------------------------------------------------------------------

let cachedDriver: StorageDriver | null = null;

export function getStorageDriver(): StorageDriver {
  if (cachedDriver) return cachedDriver;
  const env = getEnv();

  if (env.STORAGE_DRIVER === 'local') {
    cachedDriver = new LocalStorageDriver(env.STORAGE_LOCAL_PATH);
    return cachedDriver;
  }

  if (env.STORAGE_DRIVER === 'appwrite') {
    // getEnv() already refuses to validate STORAGE_DRIVER=appwrite
    // without these three set, but TypeScript still sees them as
    // optional -- the check stays for that, not because it can fail here.
    if (!env.APPWRITE_ENDPOINT || !env.APPWRITE_PROJECT_ID || !env.APPWRITE_API_KEY) {
      throw new Error(
        'APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID and APPWRITE_API_KEY are required when STORAGE_DRIVER=appwrite.',
      );
    }
    cachedDriver = new AppwriteStorageDriver(
      env.APPWRITE_ENDPOINT,
      env.APPWRITE_PROJECT_ID,
      env.APPWRITE_API_KEY,
      env.APPWRITE_BUCKET_ID,
    );
    return cachedDriver;
  }

  throw new Error(`Storage driver "${env.STORAGE_DRIVER}" is not implemented yet.`);
}

/** Test helper: forget the cached driver so a changed env is re-read. */
export function resetStorageDriverCache(): void {
  cachedDriver = null;
}

const EXTENSION_BY_CONTENT_TYPE: Record<string, string> = {
  'application/pdf': '.pdf',
  'text/html': '.html',
  'application/xhtml+xml': '.html',
  'text/plain': '.txt',
};

/** Falls back to a generic extension for a content type we don't recognize. */
export function extensionForContentType(contentType: string): string {
  const bare = contentType.split(';')[0].trim().toLowerCase();
  return EXTENSION_BY_CONTENT_TYPE[bare] ?? '.bin';
}
