import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

// The spec's content is fixed at build/deploy time (generated by
// `npm run openapi:generate`, not per-request) -- static, cacheable.
export const dynamic = 'force-static';

/**
 * Serves openapi/gpt-actions.yaml so it can be imported by URL when
 * configuring the Custom GPT's Actions (GPT editor -> Configure ->
 * Actions -> Import from URL), rather than requiring a copy-paste of
 * the file contents.
 */
export async function GET(): Promise<Response> {
  const content = await readFile(join(process.cwd(), 'openapi', 'gpt-actions.yaml'), 'utf8');
  return new Response(content, {
    headers: {
      'content-type': 'application/yaml; charset=utf-8',
      'cache-control': 'public, max-age=300',
    },
  });
}
